### ISSUE TITLE
Make the onboard switch's I2C interface available to a CM4 module

### ISSUE THREAD

**Issue by jdimpson** [DeskPi-Team/super6c#28]
According to [the data sheet](https://datasheet.lcsc.com/lcsc/2208101101_Realtek-Semicon-RTL8370N-VB-CG_C2803243.pdf) the RTL8370N is a full manageable switch. I am probably oversimplifying, but it looks like all this requires is for teh I2C pins of the switch chip to be connected to those of one of the CM4 devices. It is a shame to be unable to set VLANs, utilize the access controls and QoS, Port Mirroring, and other advanced features of this switch chip.

**Comment by yoyojacky** [comment]
Actually, this motherboard primarily integrates the CM4 network cards into the environment of the switch chip, allowing all CM4 modules to achieve data forwarding similar to a switch backplane through the internal hardware network. In reality, the ETH0 network interface of each CM4 module, as seen in the Raspberry Pi system, is connected to a local network. Regarding the advanced features of the switch, it may require support at the system level. The hardware we provide may not support VLAN segmentation, but if you want to implement access control and QoS, you can try using application-level IPTABLES. This is a baseboard for a cluster, and it might be more suitable for cluster applications rather than network devices.
