### ISSUE TITLE
super6c nodes individual console access

### ISSUE THREAD

**Issue by NikolayDachev** [DeskPi-Team/super6c#31]
Is there any way to have some sore of software serial console access to individual nodes ?
For example if have a issue with one of the cm4 modules to boot to be able to access with "serial console" via other working node ?

**Comment by yoyojacky** [comment]
By default, you can insert each CM4 into the #1 slot to configure the network and SSH server. After configuration, connect the other slots and perform remote debugging via the network. This is because only #1 provides HDMI output, while others can only be operated through the serial port pins. For information about the USB ports and GPIO pins next to each CM4 module, please refer to the instructions on wiki.deskpi.com.
